// movies

const movieInvetory = [
    { title: "The Odyssey", year: 2026, director: "Christopher Nolan", 
        rating: 8.4, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRriIyTNYRDfuTTJ_df1I3qoM49oy4OKQguEveov3cb8Q&s=10" },
    { title: "Mad Max: Fury Road", year: 2015, director: "George Miller", rating: 8.1, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROYaMOIGualCWfDR3qTq9THYc2uNSK613eRgB1dqKEcg&s=10" },
    { title: "Parasite", year: 2019, director: "Bong Joon-ho", rating: 8.5, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQbY63zr-6FfCJ3IkwLaEErMVfBz9EJDIhM1YuWAwkfA&s=10" },
    { title: "Coraline", year: 2009, director: "Henry Selick", rating: 7.8, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlYDlLhwPXoI0DvneXZvrGVR6K2Srdkfy4PdjAIv7SEA&s" },
    { title: "Spirited Away", year: 2001, director: "Hayao Miyazaki", rating: 8.6, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6_ZMTP-AmWnarhhnLqfSARQzpCthiz-qhJly8ptUfwg&s=10" },
    { title: "Jurassic Park", year: 1993, director: "Steven Spielberg", 
        rating: 8.2, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYkQmIeKnp-g4ZR9lqaEq2uUGCi8Y3T-ohQFhbqaEYJw&s=10" },
    { title: "Whiplash", year: 2014, director: "Damien Chazelle", rating: 8.5, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjrtD3TK9hzLBj6LpfrxaMEKNotMDqo4m2iWvrAJAuZA&s" },
    { title: "McFarland, USA", year: 2015, director: "Nici Caro", rating: 7.4, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEguVVSh9u7c32TL11Ugaje7qqlKCX3kWFA7K6xWy0PQ&s" },
    { title: "Everything Everywhere All at Once", year: 2022, director: "Daniel Kwan", 
        rating: 7.7, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQEc0oPE2FZ7IU1wcnA8dY0js6dDJb33uvK_BRqPn6KA&s=10" },
    { title: "Inside Out", year: 2015, director: "Pete Docter", rating: 8.1, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYj-bRrmH6IJCbzmtau42m9wWUmkcnNh2eFZuak2UWzQ&s=10" },
    { title: "Sicario", year: 2015, director: "Denis Villeneuve", rating: 7.7, 
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxALs172_-tssPxVRa7oIdmA_-CXpTg4_PtXu1WBeJzw&s=10" },
    { title: "Jaws", year: 1975, director: "Steven Spielberg", 
        rating: 8.1, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPQqW5NHXhY2GvhGYKluVgra-rI20Fxk1vCidGOPRA8w&s=10" },
    {title: "Spider-Man: Brand New Day", year: 2026, director:"Destin Daniel Crettor", 
        rating: 8.0, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS32i4a2MkDqOPOS9ExBuTvCQBxEuaTsnhkOJjX-O84Jxi4CrIBYs4sxuwfmEfvAtrluRV2&s=10"},
]