// movies

const movieInventory = [
    { title: "The Odyssey", year: 2026, director: "Christopher Nolan", rating: 8.4, genre: "action",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRriIyTNYRDfuTTJ_df1I3qoM49oy4OKQguEveov3cb8Q&s=10" },
    { title: "Mad Max: Fury Road", year: 2015, director: "George Miller", rating: 8.1, genre: "action",
        watched: true, dateWatched: "2026-08-22",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROYaMOIGualCWfDR3qTq9THYc2uNSK613eRgB1dqKEcg&s=10" },
    { title: "Parasite", year: 2019, director: "Bong Joon-ho", rating: 8.5, genre: "thriller",
        watched: true, dateWatched: "2026-09-20",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQbY63zr-6FfCJ3IkwLaEErMVfBz9EJDIhM1YuWAwkfA&s=10" },
    { title: "Coraline", year: 2009, director: "Henry Selick", rating: 7.8, genre: "horror",
        watched: true, dateWatched: "2026-09-15",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlYDlLhwPXoI0DvneXZvrGVR6K2Srdkfy4PdjAIv7SEA&s" },
    { title: "Spirited Away", year: 2001, director: "Hayao Miyazaki", rating: 8.6, genre: "drama",
        watched: true, dateWatched: "2026-09-10",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6_ZMTP-AmWnarhhnLqfSARQzpCthiz-qhJly8ptUfwg&s=10" },
    { title: "Jurassic Park", year: 1993, director: "Steven Spielberg", rating: 8.2, genre: "scifi",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYkQmIeKnp-g4ZR9lqaEq2uUGCi8Y3T-ohQFhbqaEYJw&s=10" },
    { title: "Whiplash", year: 2014, director: "Damien Chazelle", rating: 8.5, genre: "drama",
        watched: true, dateWatched: "2026-08-30",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjrtD3TK9hzLBj6LpfrxaMEKNotMDqo4m2iWvrAJAuZA&s" },
    { title: "McFarland, USA", year: 2015, director: "Nici Caro", rating: 7.4, genre: "drama",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEguVVSh9u7c32TL11Ugaje7qqlKCX3kWFA7K6xWy0PQ&s" },
    { title: "Everything Everywhere All at Once", year: 2022, director: "Daniel Kwan", rating: 7.7, genre: "comedy",
        watched: true, dateWatched: "2026-08-05",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQEc0oPE2FZ7IU1wcnA8dY0js6dDJb33uvK_BRqPn6KA&s=10" },
    { title: "Inside Out", year: 2015, director: "Pete Docter", rating: 8.1, genre: "comedy",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYj-bRrmH6IJCbzmtau42m9wWUmkcnNh2eFZuak2UWzQ&s=10" },
    { title: "Sicario", year: 2015, director: "Denis Villeneuve", rating: 7.7, genre: "thriller",
        watched: true, dateWatched: "2026-08-14",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxALs172_-tssPxVRa7oIdmA_-CXpTg4_PtXu1WBeJzw&s=10" },
    { title: "Jaws", year: 1975, director: "Steven Spielberg", rating: 8.1, genre: "thriller",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPQqW5NHXhY2GvhGYKluVgra-rI20Fxk1vCidGOPRA8w&s=10" },
    { title: "Spider-Man: Brand New Day", year: 2026, director: "Destin Daniel Cretton", rating: 8.0, genre: "action",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS32i4a2MkDqOPOS9ExBuTvCQBxEuaTsnhkOJjX-O84Jxi4CrIBYs4sxuwfmEfvAtrluRV2&s=10" },
    { title: "Gladiator", year: 2000, director: "Ridley Scott", rating: 8.5, genre: "action",
        watched: true, dateWatched: "2026-09-28",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT60xuUrNHrRi7Og3A70kJmykJYIDGbDNk4I9xULdmqzQ&s" },
    { title: "10 Things I Hate About You", year: 1999, director: "Gil Junger", rating: 7.4, genre: "romance",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF7-lmPybcdJhSJ2Ye4heZFjzVG4SGzTY_NNjHAVyUtQ&s=10" },
    { title: "Avatar: The Way of Water", year: 2022, director: "James Cameron", rating: 7.5, genre: "scifi",
        watched: false, dateWatched: null,
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf_21ac3w7tjl0d1mjn9jOArW9SzBbS3vp6l97gDVgkQ&s=10" }
]